# Job on the shortq
#PBS -l nodes=1:ppn=10,mem=20gb,pvmem=22gb
# It should be allowed to run for up to 1 hour
#PBS -l walltime=08:00:00
# Name of job.
#PBS -N split_test
# Join STDERR TO STDOUT.  (omit this if you want separate STDOUT AND STDERR)
#PBS -j oe
date -u
echo "finding tweets in parks"
cd /users/a/s/aschwa15/twitter/multipark_tweets/src/scripts
python park_split.py OH_Cleveland_3916000.json
echo "finish tweets in parks"
date -u